class _BotCommands:
    def __init__(self):
        self.LeechCommand = 'leechmacki'
        self.gLeechCommand = 'gleechbhosdi'
        self.ExtractCommand = 'extractgandu'
        self.gExtractCommand = 'gextractmced'
        self.ArchiveCommand = 'archivepagla'
        self.gArchiveCommand = 'garchiveiya'
        self.telegramfleechCommand = 'tleechiya'
        self.telegramexleechCommand = 'tleechexbhaiya'
        self.gcloneCommand = 'gcloneiaoa'
        self.YtdlCommand = 'ytdl'
        self.gYtdlCommand = 'gytdltiya'
        self.PytdlCommand = 'pytdltiya'
        self.gPytdlCommand = 'gpytdltiya'        
        self.ToggleDocCommand = 'toggledoc'
        self.ToggleVidCommand = 'togglevid'
        self.SaveCommand = 'savethumb'
        self.ClearCommand = 'clearthumb'
        self.RenameCommand = 'rename'
        self.StatusCommand = 'statustiya'
        self.SpeedCommand = 'speedtesttiya'
        self.HelpCommand = 'helputiya'
        self.LogCommand = 'longotiya'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
